# Generated by Django 5.2.8 on 2025-11-18 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stock_options_alter_purchase_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='item_total',
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum Retail Price.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price paid to the supplier.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit based on batch cost or product supplier cost.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price (legacy field). Minimum 0.01.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sold_quantity',
            field=models.IntegerField(help_text='Number of units sold.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Optional global expiry date (if not using batch-level expiries).', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Total quantity aggregated from active batches.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'batch_number')},
            },
        ),
        migrations.AddField(
            model_name='saleitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch from which stock was deducted.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batch'),
        ),
    ]
