# Generated by Django 5.2.8 on 2025-11-19 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_saleitem_item_total_product_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='batch_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_purchases', to='inventory.batch'),
        ),
    ]
