# Generated by Django 5.2.8 on 2025-11-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchase_batch_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='batch_number_input',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expiry_date_input',
            field=models.DateField(blank=True, null=True),
        ),
    ]
